version: '3'

services:
  database:
    container_name: ContainerDockerCompose
    image: mongo:6.0.6
    volumes:
      - VolumenDockerCompose:/var/lib/docker/volumes/VolumenDockerCompose/_data
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mauricioro
      - MONGO_INITDB_ROOT_PASSWORD=chatarra2003
    command: ['--auth']
  dbmanager:
    depends_on:
      - database
    container_name: mongoExpress
    image: mongo-express:1.0.0-alpha.4
    
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mauricioro
      - ME_CONFIG_MONGODB_ADMINPASSWORD=chatarra2003
      - ME_CONFIG_MONGODB_SERVER=ContainerDockerCompose
    restart: always

volumes:
  VolumenDockerCompose:
    external: false